"""Apply 1 to many with Location as parent and Book as child

Revision ID: 4a5fbaa9911b
Revises: 1f5cc024a310
Create Date: 2021-07-26 15:08:02.204561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5fbaa9911b'
down_revision = '1f5cc024a310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Book', 'Location', ['location_id'], ['id'])
    op.drop_constraint('Location_book_id_fkey', 'Location', type_='foreignkey')
    op.drop_column('Location', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Location_book_id_fkey', 'Location', 'Book', ['book_id'], ['id'])
    op.drop_constraint(None, 'Book', type_='foreignkey')
    op.drop_column('Book', 'location_id')
    # ### end Alembic commands ###
